fix(lib): possible 'length' undefined from link rel styleSheets
kimmobrunfeldt/fix-outline pull request #2
Opened 2017-04-22 06:50 UTC by artisin

__Description__:
CLOSES #2

If as user defines `link rel="stylesheet"` before their `.css` asset it will throw since a `link` without an attached stylesheet does not have `cssRules`. For example linking a font asset as such, `<link href="https://fonts.googleapis.com/css?family=Asar" rel="stylesheet">`.

2017-09-15 05:20 UTC, joeldbirch requested changes
Thanks for fixing this and taking time to make a pull request, I'm using your fix and it works great. I hope it gets merged soon.

Please note that the word "styleSheets" in the comment on line 58 is incorrectly spelt. I'd hate for that to be the cause of it not being merged, so I thought I'd let you know.

2017-09-20 21:36 UTC, artisin commented
Haha, that I did. Fixed the spelling error.

2017-09-27 23:15 UTC, joeldbirch commented
Hoping for a merge, please @kimmobrunfeldt

2017-10-03 22:26 UTC, merged

2017-10-03 22:27 UTC, kimmobrunfeldt commented
Sorry for taking so long. Trying to release soon.